version: '3.8'
services:
  db:
    volumes: []
  web:
    ports:
      - "8001:8000"
    environment:
      DJANGO_SETTINGS_MODULE: "selenium_settings"
    volumes: []
  selenium-hub:
    image: selenium/hub:3.141.59-20200409
    ports:
      - "4444:4444"
  selenium-firefox:
    image: selenium/node-firefox:3.141.59-20200409
    environment:
      HUB_HOST: "selenium-hub"
      HUB_PORT: "4444"
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
